spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  data:
    redis:
      host: ${REDIS_HOST:-localhost}
      port: ${REDIS_PORT:-6379}

  jpa:
    show-sql: false

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics

logging:
  level:
    org.springframework.test.context.support.AnnotationConfigContextLoaderUtils: WARN

app:
  security:
    jwt:
      secret: ${JWT_SECRET}