CREATE TABLE inventory_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL,
    quantity_on_hand INTEGER NOT NULL DEFAULT 0,
    quantity_reserved INTEGER NOT NULL DEFAULT 0,
    reorder_threshold INTEGER NOT NULL DEFAULT 0,
    version BIGINT NOT NULL DEFAULT 0,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_inventory_product FOREIGN KEY (product_id) REFERENCES products (id),
    CONSTRAINT uq_inventory_product UNIQUE (product_id),
    CONSTRAINT ck_inventory_on_hand_gte_zero CHECK (quantity_on_hand >= 0),
    CONSTRAINT ck_inventory_reserved_gte_zero CHECK (quantity_reserved >= 0),
    CONSTRAINT ck_inventory_reserved_lte_on_hand CHECK (quantity_reserved <= quantity_on_hand)
);