
CREATE TABLE inventory_reservations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    quantity INTEGER NOT NULL,
    status VARCHAR(32) NOT NULL,
    expires_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_reservations_order FOREIGN KEY (order_id) REFERENCES orders (id),
    CONSTRAINT fk_reservations_product FOREIGN KEY (product_id) REFERENCES products (id),
    CONSTRAINT ck_reservations_qty_gt_zero CHECK (quantity > 0),
    CONSTRAINT ck_reservations_status CHECK (status IN ('ACTIVE', 'RELEASED', 'CONSUMED', 'EXPIRED'))
);

CREATE INDEX idx_reservations_order_id ON inventory_reservations (order_id);
CREATE INDEX idx_reservations_product_id ON inventory_reservations (product_id);
