
CREATE TABLE payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    provider VARCHAR(64) NOT NULL,
    status VARCHAR(32) NOT NULL,
    amount NUMERIC(12,2) NOT NULL,
    transaction_reference VARCHAR(128),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_payments_order FOREIGN KEY (order_id) REFERENCES orders (id),
    CONSTRAINT ck_payments_amount_gte_zero CHECK (amount >= 0),
    CONSTRAINT ck_payments_status CHECK (status IN ('PENDING',
                                                    'AUTHORIZED',
                                                    'CAPTURED',
                                                    'FAILED',
                                                    'REFUNDED'))
);

CREATE INDEX idx_payments_order_id ON payments (order_id);
